### ISSUE TITLE
Zip File

### ISSUE THREAD

**Issue by cconsoli** [ArnaudDx/Google-map-store-page-prestashop-1.7#19]
The file gives an error that says:
"This file isn't a module good for an ZIP format".
What can we do? 
We download the zip directly from this site.
Another question, do you know how to put the module in other site?

Thanks.

**Comment by realmofevil** [comment]
See how the folder in the zip should look like from another module. Then make the zip and upload it.

**Comment by wop-webmaster** [comment]
Hello. Download the zip file. Unzip it locally. Take the folder "storeggmap" and "README.md" and zip it. Upload it and install, It should work then.

**Comment by ArnaudDx** [comment]
it seems resolved (2yers later :))
