### ISSUE TITLE
Icon not working (Prestashop 1.7.8.8)

### ISSUE THREAD

**Issue by rcoussy-16h33** [ArnaudDx/Google-map-store-page-prestashop-1.7#28]
When i upload an icon in the module it does not display in front-office. I can see it in back-office though.
Tried uploading a PNG and a JPG but nothing works. Only the default Google marker is displayed when there is no icon uploaded.

<img width="886" alt="Capture d’écran 2023-01-16 à 16 45 44" src="https://user-images.githubusercontent.com/81374618/212718014-330f11a8-1b8c-438f-8d07-251c9f40731a.png">

Prestashop version 1.7.8.8
PHP version 7.4

**Comment by ArnaudDx** [comment]
Sorry @rcoussy-16h33 for the delay...

Does it finally worked?
