### ISSUE TITLE
Multilinguage issue

### ISSUE THREAD

**Issue by tmsio** [ArnaudDx/Google-map-store-page-prestashop-1.7#29]
Hello i have multilinguage version and i see my shops only in Italy version but not in english version

This is the link

Italy verfion ok:
https://www.naviflow.it/negozi
Eng verfion KO:
https://www.naviflow.it/en/shops

Thank You regards.
Emiliano

**Comment by ArnaudDx** [comment]
Sorry @tmsio  for the delay...

I looked up on the two urls and I see correctly the points on the map.
Does it working fine for you?
