### ISSUE TITLE
It stopped working with the new requeriments for a callback function in the api call.

### ISSUE THREAD

**Issue by ipaelo** [ArnaudDx/Google-map-store-page-prestashop-1.7#31]
Hi,

First of all, thank you for this module.

We have installed your module and it was working fine for a few months.

Now, it stopped to search the stores and show the map.

I have solved the map visualization adding the call to the google api in the head of the website:

<script src="https://maps.googleapis.com/maps/api/js?key=OUR_API_KEY&callback=Function.prototype" type="text/javascript"></script>

But searching, I don´t know how to solve it.

Can you check it, please?

I think that I didn´t find where to add the callback in your code.

If you want to check it: https://matarrania.com/tiendas

Regards

**Comment by ArnaudDx** [comment]
Hi @ipaelo.

Wich version of PrestaShop are you using?

I see some errors in console on your store page. Can you resolve them before trying again?

**Comment by ArnaudDx** [comment]
I juste checked my own demo shop.

I don't see any row like it  on your page :
`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=xxxxx-xxx-xxx-xxx&libraries=places" ></script>`

**Comment by ipaelo** [comment]
This is a PS 8.0.1.

I have added &libraries=places to the URL and the search is working now!!!

But in 1.7 I haven´t add this line to the header.   

The map is working but the results aren´t.

I have to check where this error comes:

Uncaught SyntaxError: Unexpected token '<'

**Comment by ArnaudDx** [comment]
Hum it's strange.
You do not need to add  this call to google api manually.
This is by this line, into `hookActionFrontControllerSetMedia()` who does the job

https://github.com/ArnaudDx/Google-map-store-page-prestashop-1.7/blob/e98da45aa72bb1df558042c3e18c782a6259bcaa/storeggmap.php#L517

**Comment by ipaelo** [comment]
May be change the hook name?

I have try everything uninstalled, desactive it, delete, install again, etc…

**Comment by ArnaudDx** [comment]
Hi
Sorry, I don't know what to say.

StoreGgMap.js and front.js are successfully added on your page. I don't know why google script not.

**Comment by ipaelo** [comment]
Hello,

I am surprised like you.  I was thinking of hooks names 1.7 vs 8.0 or
something like that.

Thank you so much
